[package]
name = "vocksel/class"
description = "A super simple approach to making classes in Roblox"
version = "0.1.1"
authors = [ "David Minnerly <me@vocksel.com>" ]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "*.spec.lua"
]

[dependencies]
TestEZ = "roblox/testez@0.4.1"